### PR TITLE
Add measures port tah

### PR DESCRIPTION
**Pull request by bitsofbits**
I more or less got it to work, although there are a few rough edges still. I'm getting too tired to focus on this more tonight, so hopefully you can pick this up and run with it in (your) morning. The rough edges:

* I'm getting some mysterious points with MMSI of zero sometimes that shouldn't be there.  I filtered them out "by hand" in the one place the caused problems, but we should figure out where they are coming from. You can see this at the end of Compare_single_models
where I have to manually remove them from new_transits.

* The data needs to be sorted and points with missing values need to be removed (or at least
not included in the stats). Not wanting to mess with rolling_measures, I'm currently filtering the points with missing values out in vessel-scoring/add measures. I also sort all of the points in scripts/add_measures. I'm son't know if either of these are in the right place to play nice with the pipeline.

Other than that it seems to be working; see Compare_single_models and Broken_model. 
I touched a fair number of files, here's a quick summary of what changed:

- scripts/add_measures: 

    - add support for default values so that all missing values can be set to some values
                
    -  *sort input*

scripts/kristina_to_numpy:

    - rescale the unscaled data from kristina

vessel_scoring/data.py: 

    - remove code adding logs

    - make more robust against mmsi with few or now fishing scores

vessel_scoring/utils.py: 

     - fixed messages_to_numpy

     - fixed numpy_to_messages

vessel_scoring/add_messages: 

     - fix course stddev to use cos/sin trick

     - filter out messages with missing values in AddMeasures

### CODE REVIEW

**Comment by bitsofbits** [comment]
All of the npz files from my datasets directory are uploaded to Google drive at datasets/TAH_snapshot2.
(Note the *2*). 

Good luck in the morning!

**Comment by bitsofbits** [comment]
@egil, one other thing I forgot to mention; At the moment scripts/add_measures is set up to only add a single window. This is to speed things up for testing, but we should back that out after the current rush is over.

**Comment by egil** [comment]
@bitsofbits, I think you tagged the wrong "egil" in your comment above :)

**Comment by bitsofbits** [comment]
@egil, Sorry about that!

@redhog, see comment two above.

**Pull request merged**
