### PR TITLE
Compare models For David K to use when showing off new models

### PR DESCRIPTION
**Pull request by bitsofbits**
Add a new Comparison Notebook that shows the difference between the legacy (old), Logistic (current) and Logistic per gear type (near future) models.

Not yet fully baked.

### CODE REVIEW

**Comment by bitsofbits** [comment]
@redhog: please check this and make sure that:

- [ ] Legacy model has same time window as what *was* in the pipeline

- [ ] Logistic model has same time windows and order as what *is* in the pipeline

**Comment by bitsofbits** [comment]
@davidkroodsma , I think the comparison in
 [Model Comparisons.ipynb](https://github.com/GlobalFishingWatch/vessel-scoring/blob/compare-models-for-kroodsma/Model%20Comparisons.ipynb)
 in this branch is addressed by 
[Compare-Models.ipynb](https://github.com/GlobalFishingWatch/vessel-scoring/blob/master/notebooks/Compare-Models.ipynb) in master. Please
take a look and see if that's the case. If not let me know what's missing and I'll incorporate
anything that is missing. If `Compare-Models` is OK as is, I'll go ahead and delete this PR and 
and branch.

/cc @redhog

**Comment by enriquetuya** [comment]
@bitsofbits what's missing on this ticket, the last comment you sent @davidkroodsma is 3 months old.

**Comment by bitsofbits** [comment]
@enriquetuya , this is stale at this point, closing.

**Pull request closed without merging**
